language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
  
install:
  - julia setup.jl
script:
  - julia sis_reject.jl 10 graph_10k_5p_Infected.txt sis_model_out.txt

